### ISSUE TITLE
Responsive emails with the ability to import HTML

### ISSUE THREAD

**Issue by maryia-kabash** [artf/grapesjs-preset-newsletter#45]
Hello @artf, and first of all, thank you for a great job on GrapesJS!

I would like to hear your opinion on the following case:
As a user I would like not only to create a responsive email (which is accomplished with the help of grapes-mjml), but also to be able to import an HTML tempate (this one is archieved by this plugin). But unfortunately I cannot have both of these features. 

As far as I know there is no way to convert HTML to MJML, so import HTML in grapes-mjml is not really doable (please correct me if I'm wrong). Then, is there a way to create responsive columns in newsletter plugin? Maybe you plan to support conditional tags or have a workaround here?

Thanks in advance,
Maryia

**Comment by artf** [comment]
> As far as I know there is no way to convert HTML to MJML, so import HTML in grapes-mjml is not really doable (please correct me if I'm wrong).

Correct, but to be honest I don't even see the advantage of converting HTML to MJML

> As a user I would like not only to create a responsive email (which is accomplished with the help of grapes-mjml), but also to be able to import an HTML tempate (this one is archieved by this plugin). But unfortunately I cannot have both of these features.

Yeah, you can't import the HTML inside the MJML because it only allows its own tags, but you should be able to import responsive HTML inside this plugin. So why just not using this? You can also define your MJML-like custom components and compile them to your HTML and still be able to import extra HTML
